export   const notifi_data = [
    {
      id: 1,
      name: 'Tom',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '2 minutes ago',
      type: 1,
    },
    {
      id: 2,
      name: 'Thomas',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '3 minutes ago',
      type: 2,
    },
    {
      id: 3,
      name: 'John',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '5 minutes ago',
      type: 3,
    },
    {
      id: 4,
      name: 'Tom',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '2 minutes ago',
      type: 1,
    },
    {
      id: 5,
      name: 'Thomas',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '3 minutes ago',
      type: 2,
    },
    {
      id: 6,
      name: 'John',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '5 minutes ago',
      type: 3,
    },
    {
      id: 7,
      name: 'Tom',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '2 minutes ago',
      type: 1,
    },
    {
      id: 8,
      name: 'Thomas',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '3 minutes ago',
      type: 2,
    },
    {
      id: 9,
      name: 'John',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '5 minutes ago',
      type: 3,
    },
    {
      id: 10,
      name: 'Tom',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '2 minutes ago',
      type: 1,
    },
    {
      id: 11,
      name: 'Thomas',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '3 minutes ago',
      type: 2,
    },
    {
      id: 12,
      name: 'John',
      image: fetchingUserProfileData?.userInfo.profileImageURL,
      time: '5 minutes ago',
      type: 3,
    },
  ];